package com.wilutions.com.module;

// This code was generated by joa-processor - do not modify
import com.wilutions.com.*;
import com.wilutions.joa.*;
import com.wilutions.joa.outlook.*;
@SuppressWarnings("all")
public class Module extends ComModule {

  // COM classes to be registered 
  private final Class<?>[] coclasses = {
    com.wilutions.redmineaddin.RedmineAddin.class,
  };
  public Class<?>[] getCoClasses() { return coclasses; }

  // OfficeAddin classes to be registered: 
  private final Class<?>[] addins = {
    com.wilutions.redmineaddin.RedmineAddin.class,
  };
  public Class<?>[] getAddins() { return addins; }

  // OutlookFormRegion classes to be registered 
  private final Class<?>[] formRegions = {
  };
  public Class<?>[] getFormRegions() { return formRegions; }


  private Module() {}
  private static Module module = new Module();
  public static Module getInstance() { return module; }
}
